version: '3.4'

volumes:
  geth_data:
  lighthouse_data:

services:
  geth:
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8545:8545'
      - 0.0.0.0:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/tcp
      - 0.0.0.0:${EL_P2P_PORT:-30303}:${EL_P2P_PORT:-30303}/udp
    environment:
      - EL_P2P_PORT=${EL_P2P_PORT:-30303}
    command: /usr/local/bin/geth.sh
    volumes:
      - 'geth_data:/db'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret
      - type: bind
        source: ./geth/genesis.json
        target: /config/genesis.json

  lighthouse:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    ports:
      - "5052:5052"
      - "5054:5054"
      - 0.0.0.0:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/tcp
      - 0.0.0.0:${CL_P2P_PORT:-9000}:${CL_P2P_PORT:-9000}/udp
    command: >
      lighthouse bn
      --datadir /data
      --execution-jwt /config/jwtsecret
      --execution-endpoint http://geth:8551
      --debug-level debug
      --testnet-dir /config/testnet
      --http
      --http-address 0.0.0.0
      --metrics
       --metrics-address 0.0.0.0
      --port ${CL_P2P_PORT:-9000}

    volumes:
      - lighthouse_data:/data
      - type: bind
        source: ./cl_config
        target: /config/testnet
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret