version: '3.4'

volumes:
  geth_data:
  lighthouse_data:

services:
  geth:
    build:
      context: ./geth
      dockerfile: Dockerfile.geth
    ports:
      - '8545:8545'
      - 0.0.0.0:30303:30303/tcp
      - 0.0.0.0:30303:30303/udp
    command: /usr/local/bin/geth.sh
    volumes:
      - 'geth_data:/db'
      - type: bind
        source: ./geth/geth.sh
        target: /usr/local/bin/geth.sh
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret
      - type: bind
        source: ./geth/genesis.json
        target: /config/genesis.json

  lighthouse:
    build:
      context: ./lighthouse
      dockerfile: Dockerfile.lighthouse
    ports:
      - "5052:5052"
      - "8000:8000"
      - 0.0.0.0:9000:9000/tcp
      - 0.0.0.0:9000:9000/udp
    command: >
      lighthouse bn
      --datadir /data
      --execution-jwt /config/jwtsecret
      --execution-endpoint http://geth:8551
      --debug-level debug
      --testnet-dir /config/testnet
      --http
      --boot-nodes "enr:-Iq4QAw-ZQb0IiosZgDDcK5ehLs1XmwT0BWU1E1W3ZnhlAAwAE3I46dgCsCbeB5QUwcpDmpFfveTfKF7-tiIg0KWGjqGAYXoIfe6gmlkgnY0gmlwhKEjXcqJc2VjcDI1NmsxoQN4HpB2GMFY2MzwO9hGFjqRG47OX4hGDliAG-mJNWkEr4N1ZHCCIyk,enr:-MS4QDPBabaTc8ieXJbi0XmIIwwNODQbUX4vn5EiDn1SJ9RWHr6GwMFOivD2NmFfB8xnX4aKtL13ngbK6RcYUydmCTMJh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDGtzSqUEhEBf__________gmlkgnY0gmlwhLymRc2Jc2VjcDI1NmsxoQJibuRb1qr76OpfSNMxPXjh8ZmSgGIB6vdHiBpgFnKgt4hzeW5jbmV0c4gAAAAAAAAAAIN0Y3CCIyiDdWRwgiMo,enr:-Ly4QPkqu4tkU1g1J6d4SNO0zoSmjcsR3lFBRRmN4vziZfzNZJI4etFAOH86S_CQAwD4OYUFojJxUqVlb1w45kIVp38Bh2F0dG5ldHOIAAAAAAAAAACEZXRoMpDGtzSqUEhEBf__________gmlkgnY0gmlwhJ_f2VGJc2VjcDI1NmsxoQK2YhW-8TXvOoUiBJyGtn0Dg64FZyOXPUNFXMaam6uuq4hzeW5jbmV0cwCDdGNwgiMog3VkcIIjKA"

    volumes:
      - lighthouse_data:/data
      - type: bind
        source: ./cl_config
        target: /config/testnet
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret