version: '3.4'

services:
  geth:
    image: ethpandaops/geth:mdehoog-eip4844
    ports:
      - '8545:8545'
      - '8546:8546'
      - '8547:8547'
      - '8551:8551'
      - '30303:30303'
    entrypoint: docker-entrypoint.sh
    volumes:
      - './data:/data'
      - type: bind
        source: ./geth/docker-entrypoint.sh
        target: /usr/local/bin/docker-entrypoint.sh
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret

  prysm:
    image: ethpandaops/prysm:eip4844-1-08a910e
    entrypoint: docker-entrypoint.sh
    ports:
      - "3500:3500"
      - "4000:4000"
      - "13000:13000"
    volumes:
      - './data:/data'
      - type: bind
        source: ./geth/jwtsecret
        target: /config/jwtsecret
      - type: bind
        source: ./prysm/docker-entrypoint.sh
        target: /usr/local/bin/docker-entrypoint.sh
